// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://emlqoqwcnyxakdfuntvy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVtbHFvcXdjbnl4YWtkZnVudHZ5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI1NjI4ODMsImV4cCI6MjA2ODEzODg4M30.rRFscqtj_rRB_-ftAAkEklNHBDx0KncIgcndH-fcJqE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);